title: orangutan for reddit
description: >- # this means to ignore newlines until "baseurl:"
  Android application for browsing Reddit.
github_username:  defnought

# Build settings
theme: minima

header_pages:
  -

exclude:
  - README.md
